name: rsva-g-haplotypes
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - biopython
  - pyyaml
  - jupyterlab
  - ipykernel
